watchmatch/core/urls.py
from django.urls import path

from .views import index, about


app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
]

watchmatch/rooms/urls.py
from django.urls import path

from .views import create_room, join_room, list_play_rooms


app_name = 'rooms'

urlpatterns = [
    path('create-room/', create_room, name='create_room'),
    path('join-room/', join_room, name='join_room'),
    path('list_rooms', list_play_rooms, name='list_rooms'),
]

watchmatch/users/urls.py
from django.urls import path, include

from .views import CreateUserView


app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path(
        'registration/',
        CreateUserView.as_view(),
        name='registration',
    ),
]

watchmatch/watchmatch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

handler400 = 'core.views.bad_request'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('', include('core.urls')),
    path('movies/', include('movies.urls')),
    path('rooms/', include('rooms.urls')),
    path('play_room/', include('swipes.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

watchmatch/core/views.py
import logging

from django.shortcuts import render


logger = logging.getLogger(__name__)


def index(request):
    """Главная страница"""
    template_name = 'core/index.html'
    return render(request, template_name)


def about(request):
    """Страница о проекте"""
    template_name = 'core/about.html'
    return render(request, template_name)


def page_not_found(request, exception):
    """Страница не найдена"""
    logger.warning(f"404: {request.path}")
    return render(request, 'core/404.html', status=404)


def csrf_failure(request, reason=''):
    """Ошибка csrf токена"""
    logger.warning(f"CSRF failure: {reason}")
    return render(request, 'core/403csrf.html', status=403)


def bad_request(request, exception):
    """Ошибка запроса"""
    logger.warning(f"400 Bad Request: {request.path}")
    return render(request, 'core/400.html', status=400)


def server_error(request):
    """Ошибка сервера"""
    logger.error("500 Server Error")
    return render(request, 'core/500.html', status=500)

watchmatch/templates/core/403csrf.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1 class="mb-4">Ошибка CSRF. 403</h1>
</div>
{% endblock %}

watchmatch/templates/core/about.html
{% extends "base.html" %}

{% block content %}
<div class="container text-start">
  <p class="lead">
  <p><b>WatchMatch</b> — это сервис, который помогает компаниям быстро и без споров решить главный вопрос любого вечера: что посмотреть.</p>
  <p>Многие сталкивались с ситуацией, когда выбор фильма превращается в долгие обсуждения, бесконечный скроллинг и потерю времени. WatchMatch решает эту проблему, превращая процесс выбора в простой, быстрый и увлекательный формат совместного принятия решения.</p>
  <p>Сервис работает через комнаты: пользователь создаёт комнату и приглашает друзей, после чего участники просматривают карточки фильмов и отмечают понравившиеся варианты. Когда предпочтения совпадают, появляется матч — фильм, который устроил всех участников.</p>
  <p>Важно понимать, что WatchMatch не является платформой для просмотра контента. Его задача — помочь компаниям принять решение и упростить выбор, сделав его частью развлечения.</p>
  <b>Основные возможности:</b>
  <ul>
    <li>создание приватных комнат
    <li>совместный выбор фильмов в игровом формате
    <li>быстрый поиск совпадений предпочтений
    <li>минималистичный и понятный интерфейс
    <li>превращение выбора фильма в совместный опыт
  </ul>
  <b>WatchMatch отлично подходит для:</b>
  <ul>
    <li>вечеров с друзьями
    <li>свиданий
    <li>семейных просмотров
    <li>онлайн-созвонов
    <li>ситуаций, когда сложно договориться
  </ul>
  <b>О разработчике</b>
  <p>Проект создаётся как pet-project разработчиком Кремешным Романом.
    WatchMatch появился из личного опыта — частых ситуаций,
    когда выбор фильма в компании занимал больше времени, чем сам просмотр.</p>
  <p>Роман развивает проект как эксперимент в backend-разработке и продуктовой логике, уделяя внимание:</p>
  <ul>
    <li>удобству пользовательского опыта
    <li>простоте интерфейса
    <li>реалистичным сценариям использования
    <li>постепенному развитию функциональности
    <li>практическому применению технологий веб-разработки
  </ul>
  <p>Главная цель проекта — превратить выбор фильма из проблемы в совместное развлечение и создать сервис,
    который действительно решает повседневную задачу пользователей.</p>
  </p>
</div>
{% endblock %}

watchmatch/templates/core/index.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1 class="mb-4">Добро пожаловать в WatchMatch!</h1>
  <p class="lead">
    Собирайте друзей, создавайте комнаты и решайте вместе, что посмотреть!
    WatchMatch делает процесс выбора простым и веселым — больше никаких долгих поисков,
    только совместное удовольствие и отличное настроение!
  </p>
  {% if user.is_authenticated %}
    <a href="{% url 'rooms:create_room' %}" class="btn btn-primary btn-lg mt-3">Создать комнату</a>
    <a href="{% url 'rooms:join_room' %}" class="btn btn-primary btn-lg mt-3">Подключиться к комнате</a>
  {% else %}
    <a href="{% url 'users:registration' %}" class="btn btn-primary btn-lg mt-3">Регистрация</a>
  {% endif %}
</div>
{% endblock %}