watchmatch/core/urls.py
from django.urls import path

from .views import index, about


app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
]

watchmatch/watchmatch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

handler400 = 'core.views.bad_request'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('', include('core.urls')),
    path('movies/', include('movies.urls')),
    path('rooms/', include('rooms.urls')),
    path('play_room/', include('swipes.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

watchmatch/templates/includes/footer.html
<footer>
  <a href="{% url 'core:about' %}">2026 WatchMatch.</a>
</footer>

watchmatch/templates/includes/navbar.html
{% load static %}

{% with request.resolver_match.view_name as view_name %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <!-- Логотип слева -->
    <a class="navbar-brand" href="{% url 'core:index' %}">
      <img src="{% static 'img/logo.png' %}" alt="WatchMatch" height="40">
    </a>

    <!-- Кнопка для мобильного меню -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Меню справа -->
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'core:index' %}active{% endif %}" href="{% url 'core:index' %}">Главная</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'movies:list_movies' %}active{% endif %}" href="{% url 'movies:list_movies' %}">Рандомный фильм</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'rooms:create_room' %}active{% endif %}" href="{% url 'rooms:create_room' %}">Создать комнатy</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'rooms:join_room' %}active{% endif %}" href="{% url 'rooms:join_room' %}">Подключиться</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'rooms:list_rooms' %}active{% endif %}" href="{% url 'rooms:list_rooms' %}">Список комнат со мной</a>
        </li>
        <span class="navbar-text ms-4">Пользователь: <b>{{ user.username }}</b></span>
        <li class="nav-item">
          <form method="post" action="{% url 'users:logout' %}" >
            {% csrf_token %}
            <button type="submit" class="nav-link">Выйти</button>
          </form>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link{% if view_name == 'users:login' %} active {% endif %}" href="{% url 'users:login' %}">Войти</a>
        </li>
        {% endif %}
      </ul>
      </ul>
    </div>
  </div>
</nav>

{% endwith %}