watchmatch/core/urls.py
from django.urls import path

from .views import index, about


app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
]

watchmatch/watchmatch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

handler400 = 'core.views.bad_request'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('', include('core.urls')),
    path('movies/', include('movies.urls')),
    path('rooms/', include('rooms.urls')),
    path('play_room/', include('swipes.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

watchmatch/rooms/forms.py
from django import forms
from django.core.validators import ValidationError

from movies.models import Genre
from .models import Room


class RoomForm(forms.ModelForm):
    """
    Форма для создания комнаты
    """
    count_participants = forms.TypedChoiceField(
        choices=[(i, i) for i in range(1, 5)],
        coerce=int,
        label='Количество участников',
        help_text='от 1 до 4 участников'
    )
    genres = forms.ModelMultipleChoiceField(
        queryset=Genre.objects.none(),
        widget=forms.CheckboxSelectMultiple,
        label='Жанр',
    )
    vote_average = forms.DecimalField(
        max_digits=4,
        decimal_places=2,
        min_value=0,
        max_value=10,
        label='Рейтинг от',
        required=False,
    )

    class Meta:
        model = Room
        fields = [
            'name',
            'count_participants',
            'genres',
            'year_start',
            'year_end',
            'adult',
            'vote_average',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['genres'].queryset = Genre.objects.all()


class JoinRoomForm(forms.Form):
    """
    Форма для подключения к комнате
    """
    room_id = forms.IntegerField(
        label='ID комнаты',
        help_text='ID вам сообщит его создатель'
    )

    def clean(self):
        cleaned_data = super().clean()
        room_id = cleaned_data.get('room_id')

        try:
            room = Room.objects.get(pk=room_id)
        except Room.DoesNotExist:
            raise ValidationError("Комната с таким ID не найдена.")

        if room.participants.count() >= room.count_participants:
            raise ValidationError("Комната заполнена, больше участников нельзя.")

        self.cleaned_data['room'] = room

        return cleaned_data

watchmatch/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>WatchMatch</title>

  {% load static %}

  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

  <link rel="icon" type="image/x-icon" href="{% static 'img/fav.ico' %}">

  <style>
    html, body {
      height: 100%;
      margin: 0;
    }

    body {
      display: flex;
      flex-direction: column;
    }

    /* Navbar приклеен */
    nav {
      position: sticky;
      top: 0;
      z-index: 1000;
    }

    /* main занимает всё пространство между nav и footer */
    main {
      flex: 1;
      display: flex;
      justify-content: center;
      align-items: center;
      text-align: center;
    }

    /* Footer всегда снизу */
    footer {
      text-align: center;
      padding: 10px 0;
      background: #f8f9fa;
    }

    footer a {
      color: inherit;
      text-decoration: none;
    }

    .poster-container {
      display: flex;
      justify-content: center; /* центрируем по горизонтали */
      margin-bottom: 20px;    /* отступ под постером */
    }

    .poster {
      max-width: 300px; /* максимальная ширина постера */
      height: auto;     /* сохраняем пропорции */
      width: 100%;      /* адаптация под контейнер */
    }

    #id_genres {
      padding-left: 0;
      list-style: none;
    }

    #id_genres li {
      margin-bottom: 5px;
    }

    .room_info {
    margin: 2px 0;      /* уменьшает отступ сверху и снизу */
    line-height: 1.2;   /* уменьшает межстрочный интервал */
  }
  </style>
</head>
<body>
  <!-- Bootstrap JS Bundle с Popper -->
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

  {% include "includes\navbar.html" %}

  <main>
    {% block content %}{% endblock %}
  </main>

  {% include "includes\footer.html" %}

</body>
</html>