watchmatch/core/urls.py
from django.urls import path

from .views import index, about


app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
]

watchmatch/movies/urls.py
from django.urls import path

from .views import detail_movie, list_movies


app_name = 'movies'

urlpatterns = [
    path('', list_movies, name='list_movies'),
    path('<int:movie_id>', detail_movie, name='detail_movie'),
]

watchmatch/watchmatch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

handler400 = 'core.views.bad_request'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('', include('core.urls')),
    path('movies/', include('movies.urls')),
    path('rooms/', include('rooms.urls')),
    path('play_room/', include('swipes.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

watchmatch/movies/models.py
from django.db import models

from rooms.validators import validate_vote_average


class Genre(models.Model):
    """
    Жанр фильма.

    Используется для категоризации фильмов и фильтрации
    при создании комнаты.
    """

    id = models.IntegerField(
        primary_key=True,
        verbose_name='TMDB ID',
        help_text='Идентификатор с TMDB API (заполняется автоматически)'
    )
    name = models.CharField(
        max_length=50,
        verbose_name='Название',
        help_text='Название жанра'
    )

    class Meta:
        verbose_name = 'жанр'
        verbose_name_plural = 'Жанры'

    def __str__(self):
        return self.name


class Movie(models.Model):
    """
    Фильм, доступный для голосования.

    Хранит основную информацию о фильме:
    - названия
    - жанры
    - дату релиза
    - рейтинг
    - описание
    - ссылки на изображения

    Используется в механике swipe для совместного выбора фильма.
    """

    id = models.IntegerField(
        primary_key=True,
        verbose_name='TMDB ID',
        help_text='Идентификатор с TMDB API (заполняется автоматически)'
    )
    title = models.CharField(
        max_length=100,
        verbose_name='Название',
        help_text='Название на русском языке',
        null=True
    )
    original_title = models.CharField(
        max_length=100,
        verbose_name='Оригинальное название',
        help_text='Название на языке оригинала',
        null=True
    )
    genres = models.ManyToManyField(
        Genre,
        related_name='movies',
        verbose_name='Жанр',
        blank=True
    )
    release_date = models.DateField(
        verbose_name='Дата релиза',
        help_text='Дата релиза в мире',
        null=True
    )
    adult = models.BooleanField(
        verbose_name='18+',
        help_text='Контент с рейтингом 18+',
        null=True
    )
    vote_average = models.DecimalField(
        max_digits=4,
        decimal_places=2,
        verbose_name='Средний рейтинг',
        help_text='Средний рейтинг по TMDB',
        null=True,
        validators=(validate_vote_average,)
    )
    overview = models.TextField(
        verbose_name='Описание',
        help_text='Описание на русском языке',
        null=True
    )
    poster_path = models.URLField(
        verbose_name='URL постера',
        help_text='Открытый источник к постеру',
        null=True
    )
    backdrop_path = models.URLField(
        verbose_name='URL фона',
        help_text='Открытый источник к фону по фильму',
        null=True
    )

    class Meta:
        verbose_name = 'фильм'
        verbose_name_plural = 'Фильмы'

    def __str__(self):
        return f'{self.title} ({self.release_date})'

watchmatch/movies/views.py
import logging

from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from .models import Genre
from .services import get_movie_tmdb, create_and_return_movie


logger = logging.getLogger(__name__)


@login_required
def detail_movie(request, movie_id):
    """Страница конкретного фильма"""
    data = get_movie_tmdb(movie_id)

    if not data or 'id' not in data:
        logger.warning(f'Movie not found {data}, movie_id: {movie_id}')
        return render(request, "movies/movie_not_found.html", status=404)

    movie = create_and_return_movie(data)

    genre_ids = []
    for g in data.get('genres', []):
        genre_obj = Genre.objects.get_or_create(
            id=g['id'], defaults={'name': g['name']}
        )[0]
        genre_ids.append(genre_obj.id)

    movie.genres.set(Genre.objects.filter(id__in=genre_ids))
    movie.save()

    return render(request, 'movies/detail_movie.html', {'movie': movie})


@login_required
def list_movies(request):
    """Страница случайного фильма"""
    data = get_movie_tmdb()

    movie = create_and_return_movie(data)

    genre_ids = data.get('genre_ids', [])

    movie.genres.set(Genre.objects.filter(id__in=genre_ids))
    movie.save()

    return render(request, 'movies/list_movies.html', {"movie": movie})

watchmatch/templates/movies/detail_movie.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <br>
  <h1 class="mb-4">{{ movie.title }}</h1>
  <div class="poster-container">
    <img src="{{ movie.poster_path }}" alt="Постер фильма" class="poster">
  </div>
  <p class="lead">
    <b>Оригинальное название:</b> {{ movie.original_title }}<br>
    <b>Жанр:</b> {% for genre in movie.genres.all %}{{ genre.name }}{% if not forloop.last %}, {% endif %}{% endfor %}<br>
    <b>Дата релиза:</b> {{ movie.release_date }}<br>
    <b>18+:</b> {% if movie.adult %}Да{% else %}Нет{% endif %}<br>
    <b>Рейтинг:</b> {{ movie.vote_average }}<br>
    {% if movie.overview %}<b>Описание:</b> {{ movie.overview }}<br>{% endif %}
    <br>
  </p>
</div>
{% endblock %}

watchmatch/templates/movies/list_movies.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <br>
  <h1 class="mb-4">{{ movie.title }}</h1>
  <div class="poster-container">
    <img src="https://image.tmdb.org/t/p/original{{ movie.poster_path }}" alt="Постер фильма" class="poster">
  </div>
  <p class="lead">
    <b>Оригинальное название:</b> {{ movie.original_title }}<br>
    <b>Жанр:</b> {% for genre in movie.genres.all %}{{ genre.name }}{% if not forloop.last %}, {% endif %}{% endfor %}<br>
    <b>Дата релиза:</b> {{ movie.release_date }}<br>
    <b>18+:</b> {% if movie.adult %}Да{% else %}Нет{% endif %}<br>
    <b>Рейтинг:</b> {{ movie.vote_average }}<br>
    {% if movie.overview %}<b>Описание:</b> {{ movie.overview }}<br>{% endif %}
    <a href="{% url 'movies:list_movies' %}" class="btn btn-primary btn-lg mt-3">Следующий фильм</a>
    <br>
  </p>
</div>
{% endblock %}

watchmatch/templates/movies/movie_not_found.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <br>
  <h1 class="mb-4">Фильм не найден</h1>
</div>
{% endblock %}